import type { UserRole } from "@/lib/types/domain";

export type TeamSeedUser = {
  displayName: string;
  email: string;
  jobTitle: string;
  department: string;
  teamPartner: string | null;
  bio: string | null;
  avatarColor: string;
  avatarImagePath: string | null;
  role: UserRole;
};

export const teamSeedUsers: readonly TeamSeedUser[] = [
  {
    displayName: "Clint",
    email: "clint@creativesales.biz",
    jobTitle: "CEO / Executive Account Manager",
    department: "Leadership / Sales",
    teamPartner: "Michelle (SPM)",
    bio: "Dual role: CEO and EAM paired with Michelle.",
    avatarColor: "#5f4689",
    avatarImagePath: "/avatars/team/clint.png",
    role: "admin",
  },
  {
    displayName: "Michelle",
    email: "michelle@creativesales.biz",
    jobTitle: "COO / Sales Project Manager",
    department: "Leadership / Sales",
    teamPartner: "Clint (EAM), Bob (EAM)",
    bio: "Dual role: COO and SPM for both Clint and Bob teams.",
    avatarColor: "#8863b7",
    avatarImagePath: "/avatars/team/michelle.png",
    role: "admin",
  },
  {
    displayName: "Bob",
    email: "bob@creativesales.biz",
    jobTitle: "Executive Account Manager",
    department: "Sales",
    teamPartner: "Michelle (SPM)",
    bio: null,
    avatarColor: "#7c6ab0",
    avatarImagePath: null,
    role: "member",
  },
  {
    displayName: "Melanie",
    email: "melanie@creativesales.biz",
    jobTitle: "Executive Account Manager",
    department: "Sales",
    teamPartner: "Kasandra (SPM)",
    bio: null,
    avatarColor: "#b08ccb",
    avatarImagePath: "/avatars/team/melanie.png",
    role: "member",
  },
  {
    displayName: "Kasandra",
    email: "kasandra@creativesales.biz",
    jobTitle: "Sales Project Manager",
    department: "Sales",
    teamPartner: "Melanie (EAM)",
    bio: null,
    avatarColor: "#7c89d9",
    avatarImagePath: "/avatars/team/kasandra.png",
    role: "member",
  },
  {
    displayName: "Ragan",
    email: "ragan@creativesales.biz",
    jobTitle: "Executive Account Manager",
    department: "Sales",
    teamPartner: "Stacie (SPM)",
    bio: null,
    avatarColor: "#6b8ea6",
    avatarImagePath: "/avatars/team/ragan.png",
    role: "member",
  },
  {
    displayName: "Stacie",
    email: "stacie@creativesales.biz",
    jobTitle: "Sales Project Manager",
    department: "Sales",
    teamPartner: "Ragan (EAM)",
    bio: null,
    avatarColor: "#8863b7",
    avatarImagePath: "/avatars/team/stacie.png",
    role: "member",
  },
  {
    displayName: "Sandy",
    email: "sandy@creativesales.biz",
    jobTitle: "Executive Account Manager",
    department: "Sales",
    teamPartner: "Robin (SAC)",
    bio: null,
    avatarColor: "#5f4689",
    avatarImagePath: "/avatars/team/sandy.png",
    role: "member",
  },
  {
    displayName: "Robin",
    email: "robin@creativesales.biz",
    jobTitle: "Sales Account Coordinator",
    department: "Sales",
    teamPartner: "Sandy (EAM)",
    bio: null,
    avatarColor: "#7c6ab0",
    avatarImagePath: null,
    role: "member",
  },
  {
    displayName: "Chas",
    email: "chas@creativesales.biz",
    jobTitle: "Executive Account Manager",
    department: "Sales",
    teamPartner: "Heather (SPM)",
    bio: null,
    avatarColor: "#b08ccb",
    avatarImagePath: "/avatars/team/chas.png",
    role: "member",
  },
  {
    displayName: "Heather",
    email: "heather@creativesales.biz",
    jobTitle: "Sales Project Manager",
    department: "Sales",
    teamPartner: "Chas (EAM)",
    bio: null,
    avatarColor: "#7c89d9",
    avatarImagePath: "/avatars/team/heather.png",
    role: "member",
  },
  {
    displayName: "Kaelee",
    email: "kaelee@creativesales.biz",
    jobTitle: "Senior Sales Process Manager",
    department: "Support",
    teamPartner: null,
    bio: null,
    avatarColor: "#6b8ea6",
    avatarImagePath: "/avatars/team/kaelee.png",
    role: "member",
  },
  {
    displayName: "Kendal",
    email: "kendal@creativesales.biz",
    jobTitle: "Replenishment and Sales Analyst",
    department: "Support",
    teamPartner: null,
    bio: null,
    avatarColor: "#8863b7",
    avatarImagePath: "/avatars/team/kendal.png",
    role: "member",
  },
  {
    displayName: "Ashley",
    email: "ashley@creativesales.biz",
    jobTitle: "Support - Texas Teams and Reporting",
    department: "Support",
    teamPartner: null,
    bio: null,
    avatarColor: "#5f4689",
    avatarImagePath: null,
    role: "member",
  },
  {
    displayName: "Mary Alice",
    email: "maryalice@creativesales.biz",
    jobTitle: "Accounts Payable",
    department: "Support",
    teamPartner: null,
    bio: null,
    avatarColor: "#7c6ab0",
    avatarImagePath: null,
    role: "member",
  },
  {
    displayName: "Vicki",
    email: "vicki@creativesales.biz",
    jobTitle: "Director of Finance",
    department: "Support",
    teamPartner: null,
    bio: null,
    avatarColor: "#b08ccb",
    avatarImagePath: null,
    role: "member",
  },
];

export const defaultUserSeed = teamSeedUsers[0];
